
export const heroSectionData = {
    carouselItems: [
      {
        id: '1',
        imageUrl: '/unb.png',
        title: 'Master IIT-JEE Advanced',
        description: 'Ace your IIT-JEE with our comprehensive course!',
        ctaText: 'Enroll Now',
        ctaLink: '/courses/featured-iitjee-01',
        dataAiHint: "iitjee online course",
      },
      {
        id: '2',
        imageUrl: '/geek.png',
        title: 'NEET Biology Bootcamp',
        description: 'Unlock your potential with this in-depth course!',
        ctaText: 'Enroll Now',
        ctaLink: '/courses/featured-neet-01',
        dataAiHint: "neet medical course",
      },
      {
        id: '3',
        imageUrl: '/pb.png',
        title: 'NEET Biology Bootcamp',
        description: 'Unlock your potential with this in-depth course!',
        ctaText: 'Enroll Now',
        ctaLink: '/courses/featured-neet-01',
        dataAiHint: "neet medical course",
      },
    ],
    rightBanner: {
      imageUrl: 'https://i.postimg.cc/nhsP0CSS/Screenshot-2025-06-14-144740.png',
      // title: 'UPSC CSE Prep',
      // description: 'Pre-Order Now',
      // ctaText: 'Pre-Order',
      // ctaLink: '/courses/featured-gov-01',
      // bgColor: 'bg-[--primary-blue]',
      // dataAiHint: "upsc government exam",
      title: '',
      ctaText: '',
      ctaLink: '',
      bgColor: '',
      dataAiHint: "",
    },
    promoCard: {
      imageUrl: 'https://static.pw.live/5eb393ee95fab7468a79d189/ADMIN/e5a74b05-f425-4259-b1de-d6bde25e2daa.jpg',
      // title: 'Special Offer: 50% Off!',
      // ctaText: 'Claim Now',
      // ctaLink: '/offers/special',
      // dataAiHint: "online learning offer",
         title: '',
      ctaText: '',
      ctaLink: '',
      dataAiHint: "",
    },
    bottomBanners: [
      {
        imageUrl: 'https://i.postimg.cc/sDs7DqRV/Screenshot-2025-06-14-142944-1.png',
        // title: 'Tech Courses',
        // ctaText: 'Explore',
        // ctaLink: '/courses?category=computer-science',
        // bgColor: 'bg-[--accent-teal]',
        // dataAiHint: "tech course computer",
        title: '',
        ctaText: '',
        ctaLink: '',
        bgColor: '',
        dataAiHint: "",
      },
      {
        imageUrl: 'https://i.postimg.cc/m2kMHMhq/Screenshot-2025-06-14-143916-1.png',
        // title: 'Business Courses',
        // ctaText: 'Explore',
        // ctaLink: '/courses?category=business',
        // bgColor: 'bg-[--secondary-purple]',
        // dataAiHint: "business finance chart",
        title: '',
        ctaText: '',
        ctaLink: '',
        bgColor: '',
        dataAiHint: "",
      },
      {
        imageUrl: 'https://i.postimg.cc/jjMn2StK/Screenshot-2025-06-14-145131.png',
        // title: 'Udemy',
        // ctaText: 'Browse',
        // ctaLink: '/courses?platform=udemy',
        // bgColor: 'bg-[--primary-blue]',
        // dataAiHint: "udemy online learning",
        title: '',
        ctaText: '',
        ctaLink: '',
        bgColor: '',
        dataAiHint: "",
      },
      {
        imageUrl: 'https://i.postimg.cc/05YKFsB8/Screenshot-2025-06-14-145642.png',
        // title: 'Coursera',
        // ctaText: 'Browse',
        // ctaLink: '/courses?platform=coursera',
        // bgColor: 'bg-[--accent-teal]',
        // dataAiHint: "coursera online platform",
        title: '',
        ctaText: '',
        ctaLink: '',
        bgColor: '',
        dataAiHint: "",
      },
    ],
  };
