export const ineuronData = {
    sellerInfo: {
      name: 'iNeuron',
      logo: 'https://yt3.googleusercontent.com/w_SOmqeOYbkseR1IR4Sq4hTcxKRld7XgfbCDP-zuSY0SekoJruge26gzmwBsnkOx2GFERpLN2Y8=s900-c-k-c0x00ffffff-no-rj', // Placeholder logo
      tagline: 'Empowering Future Tech Leaders',
      bannerImage: '/in.png',
    },
    categories: [
      { id: 'cat1', name: '', slug: 'advance-excel', image: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6602577b894c1954dd143bc7.jpg&w=828&q=75',cta:'https://ineuron.ai/course/advance-applications-of-excel' },
      { id: 'cat2', name: '', slug: 'data-science', image: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6613a058894c1923451545f2.jpg&w=828&q=75',cta:'https://ineuron.ai/course/data-science-masters-pro-2024' },
      { id: 'cat3', name: '', slug: 'aws', image: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F65bc94411d54c4d3ba18635b.jpg&w=828&q=75',cta:'https://ineuron.ai/course/aws-series-certification' },
      { id: 'cat4', name: '', slug: 'data-analytics', image: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6639e1d0894c1956cb179179.jpg&w=828&q=75',cta:'https://ineuron.ai/course/big-data-for-beginners' },
    ],
    featuredCourses: [
      // {
      //   id: 'course1',
      //   title: 'Full Stack Web Development',
      //   image: 'https://images.unsplash.com/photo-1547658719-88a0a6f2cdac?auto=format&fit=crop&w=400&h=200',
      //   price: 4999,
      //   rating: 4.8,
      //   reviewsCount: 1200,
      //   ctaLink: '/courses/ineuron/web-dev',
      // },
      // {
      //   id: 'course2',
      //   title: 'Data Science with Python',
      //   image: 'https://images.unsplash.com/photo-1551288049-b1f3a8a4c8d8?auto=format&fit=crop&w=400&h=200',
      //   price: 5999,
      //   rating: 4.9,
      //   reviewsCount: 1500,
      //   ctaLink: '/courses/ineuron/data-science',
      // },
      // {
      //   id: 'course3',
      //   title: 'Machine Learning Bootcamp',
      //   image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e5255?auto=format&fit=crop&w=400&h=200',
      //   price: 6999,
      //   rating: 4.7,
      //   reviewsCount: 900,
      //   ctaLink: '/courses/ineuron/ml-bootcamp',
      // },
      {
        id: 'Edtech-course-1',
        title: '30 Days Fast Track Data Science Interview Preparation',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F61b30b40b733d139bc0e7fed.jpg&w=828&q=75',
        price: 5999,
        rating: 4.8,
        reviewsCount: 1250,
        ctaLink: 'https://ineuron.ai/course/30-days-fast-track-data-science-interview-preparation',
      },
      {
        id: 'Edtech-course-2',
        title: '7 End-to-End GenAI Projects Using LLMOPS And Deployment',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6638a780894c19bffb176718.jpg&w=828&q=75',
        price: 6999,
        rating: 4.7,
        reviewsCount: 900,
        ctaLink: 'https://ineuron.ai/course/7-end-to-end-genai-projects-using-llmops-and-deployment',
      },
      {
        id: 'Edtech-course-4',
        title: 'A Job Ready Bootcamp in C++, DSA and IOT',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6287516e696079bccc3b5284.jpg&w=828&q=75',
        price: 5499,
        rating: 4.5,
        reviewsCount: 600,
        ctaLink: 'https://ineuron.ai/course/a-job-ready-bootcamp-in-c-dsa-and-iot-tech-neuron',
      },
      {
        id: 'Edtech-course-6',
        title: 'Advance Applications of Excel',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6602577b894c1954dd143bc7.jpg&w=828&q=75',
        price: 2999,
        rating: 4.6,
        reviewsCount: 700,
        ctaLink: 'https://ineuron.ai/course/advance-applications-of-excel',
      },
      {
        id: 'Edtech-course-11',
        title: 'Airflow',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F621c8dacb0701c8001dbfa72.jpg&w=828&q=75',
        price: 3999,
        rating: 4.6,
        reviewsCount: 650,
        ctaLink: 'http://ineuron.ai/course/airflow',
      }
    ],
    banners: [
      {
        id: 'banner1',
        image: '/b.png',
        // title: '50% Off on All Courses!',
        title: '',
        ctaText: 'Shop Now',
        ctaLink: 'https://jobs.ineuron.ai/',
      },
      {
        id: 'banner2',
        image: '/d.png',
        // title: 'New AI Courses Launched',
         title: '',
        ctaText: 'Explore Now',
        ctaLink: 'https://ineuron.ai/one-neuron',
      },
    ],
    allCourses: [
      {
        id: 'Edtech-course-11',
        title: 'Airflow',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F621c8dacb0701c8001dbfa72.jpg&w=828&q=75',
        price: 3999,
        rating: 4.6,
        reviewsCount: 650,
        ctaLink: 'http://ineuron.ai/course/airflow',
      },
      {
        id: 'Edtech-course-12',
        title: 'Alteryx Course',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6238e99f8e583ca633037fdc.jpg&w=828&q=75',
        price: 5999,
        rating: 4.7,
        reviewsCount: 800,
        ctaLink: 'https://ineuron.ai/course/alteryx-course',
      },
      {
        id: 'Edtech-course-13',
        title: 'Alteryx',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F6218eb05dc76485e693cdfd7.jpg&w=828&q=75',
        price: 2999,
        rating: 4.5,
        reviewsCount: 500,
        ctaLink: 'https://ineuron.ai/course/alteryx-course-ba',
      },
      {
        id: 'Edtech-course-14',
        title: 'Android Chat App with Firebase',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F623c477e8af2b967a56a3cb1.jpg&w=828&q=75',
        price: 6499,
        rating: 4.8,
        reviewsCount: 900,
        ctaLink: 'https://ineuron.ai/course/android-chat-app-with-firebase',
      },
      {
        id: 'Edtech-course-15',
        title: 'Angular',
        imageUrl: 'https://ineuron.ai/_next/image?url=https%3A%2F%2Fcdn.ineuron.ai%2Fassets%2Fuploads%2Fthumbnails%2F61e81fe3c7b80a9ddcc78df2.jpg&w=828&q=75',
        price: 5499,
        rating: 4.7,
        reviewsCount: 850,
        ctaLink: 'https://ineuron.ai/course/angular',
      },
    ],
  };